### PR TITLE
Fixed an issue with the BuildURL value in the Build Information

### LINKED ISSUE #139: Build Information Url is using the agent's settings
In early versions of the Build Information step implementation the TeamCity [server URL](https://www.jetbrains.com/help/teamcity/2019.1/configuring-server-url.html) was determined from the `Administration -> Global Settings -> Server URL`.

At some point the code changed to get the server URL from the agent's settings, which isn't always the correct value because there can be network devices, like load balancers, in play that mean the agents and the UI use slightly different URLs.

This should be reverted back to using the Global Settings.

### PR DESCRIPTION
**Pull request by slewis74**
The Build Information is currently being populated with a BuildUrl that is based on the agent's understanding of the TeamCity server's Url. Unfortunately this is not always the same Url you need in order to view the build in the UI, which is why Octopus wants it, to provide a link back to the build page.

This had previously been using the value from the `Administration -> Global Settings -> Server URL` setting, which is what this PR reverts the code back to using.

Fixes #139

### CODE REVIEW

File: octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java [hunk 1]
```diff
@@ -40,146 +40,145 @@
...
-        if (commandLineArguments != null && !commandLineArguments.isEmpty()) {
-          commands.addAll(splitSpaceSeparatedValues(commandLineArguments));
+            final OctopusBuildInformation buildInformation =
+                    builder.build(
+                            sharedConfigParameters.get("octopus_vcstype"),
+                            sharedConfigParameters.get("vcsroot.url"),
+                            sharedConfigParameters.get("build.vcs.number"),
+                            restfulBuild.getBranch().getName(),
+                            createJsonCommitHistory(restfulBuild),
+                            sharedConfigParameters.get("externalBuildURL"),
```
Comment (slewis74) [inline octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java:92]: This wall of text bought to you by an IDE reformat of the code to correct it's layout. This is the key line that actually changed.

File: octopus-server/src/main/java/octopus/teamcity/server/OctopusBuildInformationBuildStartProcessor.java [hunk 2]
```diff
@@ -40,6 +43,8 @@ public void updateParameters(final BuildStartContext buildStartContext) {
           }
           buildStartContext.addSharedParameter("octopus_vcstype", vcsType);
         }
+        final String buildUrl = webLinks.getViewLogUrl(buildStartContext.getBuild());
```
Comment (slewis74) [inline octopus-server/src/main/java/octopus/teamcity/server/OctopusBuildInformationBuildStartProcessor.java:46]: This line is the crux of the whole change, it gets the URL that TeamCity says links to the build's UI page.

File: build.gradle [hunk 3]
```diff
@@ -6,7 +6,7 @@ plugins {
   id 'com.github.ben-manes.versions' version '0.36.0'
   id 'com.github.hierynomus.license' version '0.16.1'
   id 'io.spring.dependency-management' version '1.0.11.RELEASE'
-  id 'net.ltgt.errorprone' version '1.3.0'
+  id 'net.ltgt.errorprone' version '2.0.0'
```
Comment (johnsimons) [inline build.gradle:9]: Any reason to update this package?

File: octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java [hunk 4]
```diff
@@ -40,146 +40,145 @@
 
 public class OctopusBuildInformationBuildProcess extends OctopusBuildProcess {
 
-  private final File checkoutDir;
```
Comment (johnsimons) [inline octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java:43]: It looks like this code reformat causes the build to fail - https://github.com/OctopusDeploy/Octopus-TeamCity/runs/5655504829?check_suite_focus=true#step:4:57

**Review by johnsimons — APPROVED** [review]
Makes sense.
Any tests to go with it?

File: build.gradle (hunk 3 above)
Comment (slewis74) [reply build.gradle:9]: yes, because if you have a later version of the JDK installed (like I had 16) then the compile would fail.

File: octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java (hunk 4 above)
Comment (slewis74) [reply octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java]: Fixed the editor settings and corrected the formatting.

File: octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java [hunk 5]
```diff
@@ -89,8 +89,7 @@ protected OctopusCommandBuilder createCommand() {
               sharedConfigParameters.get("build.vcs.number"),
               restfulBuild.getBranch().getName(),
               createJsonCommitHistory(restfulBuild),
-              teamCityServerUrl,
-              buildIdString,
+              sharedConfigParameters.get("externalBuildURL"),
```
Comment (rain-on) [inline octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java:92]: nit: externalBulidURL or externalBuildUrl?

File: octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java [hunk 6]
```diff
@@ -52,9 +52,8 @@ public OctopusBuildInformationBuildProcess(
     final Map<String, String> sharedConfigParameters = runningBuild.getSharedConfigParameters();
 
     final BuildInfoUserData buildInfoUserData = new BuildInfoUserData(parameters);
-    final String buildId = Long.toString(runningBuild.getBuildId());
 
-    final URL buildUrl = constructBuildUrl(runningBuild, buildId);
+    final URL buildUrl = constructBuildUrl(sharedConfigParameters.get("externalBuildURL"));
```
Comment (rain-on) [inline octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java:56]: I was thinking about this - we COULD just pass a String through to the payload - there's no real need to validate this is a correctly formed URL - we're just a opaque pipe, routing data from TC --> OD.
I.e. never convert this data into a URL object, it doesn't really add value now that we're not modifying it

**Review by rain-on — APPROVED** [review]
nits only - looks good otherwise.

File: octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java (hunk 5 above)
Comment (slewis74) [reply octopus-agent/src/main/java/octopus/teamcity/agent/OctopusBuildInformationBuildProcess.java:92]: changed to make it consistent with the variable naming

File: octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java (hunk 6 above)
Comment (slewis74) [reply octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java]: I don't mind it being a Url, strong types aren't a bad thing

File: octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java [hunk 7]
```diff
@@ -52,9 +52,16 @@ public OctopusBuildInformationBuildProcess(
     final Map<String, String> sharedConfigParameters = runningBuild.getSharedConfigParameters();
 
     final BuildInfoUserData buildInfoUserData = new BuildInfoUserData(parameters);
-    final String buildId = Long.toString(runningBuild.getBuildId());
 
-    final URL buildUrl = constructBuildUrl(runningBuild, buildId);
+    String buildUrlString = sharedConfigParameters.get("externalBuildUrl");
+    if (buildUrlString == null) {
```
Comment (rain-on) [inline octopus-agent/src/main/java/octopus/teamcity/agent/buildinformation/OctopusBuildInformationBuildProcess.java:57]: nit: I'd put all this into the constructBuildUrl - and hide that there's logic around how its contstruted
